[package]
name = "structure"
version = "0.1.0"
edition = "2021"

publish = false

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4.19", features = ["serde"] }
